up:
	./run-docker.sh
kill:
	docker compose kill
start:
	docker compose start
stop:
	docker compose stop
ps:
	docker ps --filter "name=example"
rm:
	docker compose rm
exec:
	docker exec -ti example.web.app bash
logs:
	docker compose logs -f
logs-web:
	docker logs example.web.app -f
