#!/bin/bash

set -e

POSTGRES="psql --username ${DATABASE_USER} --dbname ${DATABASE_NAME}"

$POSTGRES <<EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL

echo "Creating database: ${TEST_DATABASE_NAME}. ${TEST_DATABASE_USER}"

if [ -n "$TEST_DATABASE_NAME" ]; then
    echo "Creating database: ${TEST_DATABASE_NAME}"
$POSTGRES <<EOSQL
    CREATE USER ${TEST_DATABASE_USER} SUPERUSER PASSWORD '${TEST_DATABASE_PASSWORD}';
    CREATE DATABASE ${TEST_DATABASE_NAME} OWNER ${TEST_DATABASE_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${TEST_DATABASE_NAME} TO ${TEST_DATABASE_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${TEST_DATABASE_NAME} TO ${DATABASE_USER};
EOSQL
fi
